### ISSUE TITLE
Run on startup

### ISSUE THREAD

**Issue by Zap2Shine** [Hersy/personal-login-shortcut#3] opened 2024-08-25 04:51 UTC
that as well

**Comment by Hersy** [comment] 2024-08-25 04:54
Duplicate of [#5](https://github.com/Hersy/personal-login-shortcut/issues/5)

**Comment by Hersy** [comment] 2024-08-25 04:55
Duplicate of https://github.com/Hersy/personal-login-shortcut/issues/5

**Closed as completed by Hersy** 2024-08-25 04:55 UTC
